### ISSUE TITLE
Import Data into IPAddresses including Custom DNS Fields fails 

### ISSUE THREAD

**Issue by lairsdragon** [peteeckel/netbox-plugin-dns#147]
**Versions**
NetBox Version: 3.6.9
NetBox DNS Version: 0.21.15
Python Version: 3.11.4

**Describe the bug**
I am in the process to import data from our old netdot installation into netbox and the dns plugin. The plan is to use the new IPAM coupling to import the hostnames of network object into the dns plugin and import the remaining DNS Information directly into the dns records view.

Importing into IPAddresses using the custom fields yields two problems:
- cf_ipaddress_dns_record_disable_ptr is marked as optional  "Field Options Table" in the IP Address Bulk Import page but not providing it yields an error
- cf_ipaddress_dns_zone_id requires the Zone ID instead of the zone Name which makes it difficult to create the import files in a way that they are reapplicable. (Import Data, Check Data, find errors, Rinse data from Netbox and repeat this Until all errors are fixed...)

**To Reproduce**
1. Goto /ipam/ip-addresses/import/
2. Import following CSV
```
address,status,description,dns_name, cf_ipaddress_dns_record_name,cf_ipaddress_dns_zone_id
192.0.2.85/27,active,"test","test","example.com"
```

**Expected result**
1. disable_ptr shoudl be set to false or be marked as required
2. zone_id should support search with the prodid zone name 

**Actual result**
missing cf_ipaddress_dns_record_disable_ptr yields the following error:
  ```
  <class 'ValueError'>

  'IPAddressImportForm' has no field named 'disable_ptr'.

  Python version: 3.11.4
  NetBox version: 3.6.9
  Plugins: 
    netbox_dns: 0.21.15
    netbox_qrcode: 0.0.11
  ```

Zone name instead of zone id yields:
"Record 1 cf_ipaddress_dns_zone_id: Object not found: example.com "

**Comment by peteeckel** [comment]
Hi @lairsdragon, thanks for reporting this. It seems, though, that I can't actually do anything about it. 

Importing objects with custom fields is an operation that is defined in NetBox core code, not NetBox DNS, and if you look at the custom fields you'll see that for the "Disable PTR" field there actually is a default value defined.

With the zone ID we have a similar problem: There does not seem to be a mechanism in NetBox that allows you to define specifying a different object by name instead of ID in imports.

At least the former issue seems to be a bug to me - There is a default value, the field is not required, and so NetBox should imply the default value if you don't specify the field, which it obviously doesn't.

**Comment by peteeckel** [comment]
Just a second ... I think I see what you mean.

Is it this exception?
```
Traceback (most recent call last):
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/db/models/base.py", line 1502, in full_clean
    raise ValidationError(errors)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception ({'disable_ptr': ['“None” value must be either True or False.']}), another exception occurred:
  File "/opt/netbox/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/views/generic/base.py", line 77, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/views.py", line 99, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/views/generic/bulk_views.py", line 460, in post
    new_objs = self.create_and_update_objects(form, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/views/generic/bulk_views.py", line 418, in create_and_update_objects
    if model_form.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/forms/mixins.py", line 55, in is_valid
    is_valid = super().is_valid()
               ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
    ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
    ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/forms/base.py", line 69, in _post_clean
    return super()._post_clean()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/models.py", line 488, in _post_clean
    self._update_errors(e)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/models.py", line 460, in _update_errors
    self.add_error(None, errors)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/lib64/python3.11/site-packages/django/forms/forms.py", line 400, in add_error
    raise ValueError(
```

**Comment by lairsdragon** [comment]
> Is it this exception?

Jepp, thats the exceptions

**Comment by peteeckel** [comment]
That's fortunately something I **can** do something about :-)

**Comment by peteeckel** [comment]
0.21.17 has been released and should fix the problem with `cf_ipaddress_dns_record_disable_ptr`.

**Comment by peteeckel** [comment]
Regarding the zone name - that definitely can't work, not only because NetBox does not have the required functionality for importing custom fields representing objects by name, bit also because a name does not uniquely identify a zone (while a zone ID does). There may be multiple zones with the same name, but different views.
