### ISSUE TITLE
Plugin netbox_dns does not provide a 'config' variable

### ISSUE THREAD

**Issue by netravnen** [peteeckel/netbox-plugin-dns#174]
**Versions**

- NetBox Version: 3.7.2
- NetBox DNS Version: 0.22.1
- Python Version: 3.11.2
- OS: Debian GNU/Linux 12 (bookworm)
- Container type: LXC
- Host OS: Proxmox VE 8

**Describe the bug**
Trying to run the migrate command to install the relevant DB tables fails with error msg `Plugin netbox_dns does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig subclass.`

**To Reproduce**
1. Install the plugin as described,
2. Try to run the migrate command `python /opt/netbox/netbox/manage.py migrate netbox_dns`
3. See error

**Expected result**
A successful installation.

**Actual result**
The below stacktrace below is printed to the console.

**Screenshots**

```
root@netbox # python /opt/netbox/netbox/manage.py migrate netbox_dns 
Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 760, in <module>
    plugin_config: PluginConfig = plugin.config
                                  ^^^^^^^^^^^^^
AttributeError: module 'netbox_dns' has no attribute 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 103, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 762, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_dns does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig subclass.
```

**Code Examples**
N/A

**Comment by netravnen** [comment]
From the stacktrace it looks like a coding error. If not. I am missing an installation step. I am a bit unsure what is causing the error.

**Comment by peteeckel** [comment]
Very likely a duplicate of #104

**Comment by peteeckel** [comment]
Did you perform the steps mentioned in #104?

**Comment by peteeckel** [comment]
Re-ran the tests with the latest versions: https://github.com/peteeckel/netbox-plugin-dns/actions/runs/7934536361/job/21704466588

**Comment by peteeckel** [comment]
Hi @netravnen, did you manage to fix your issue?

**Comment by peteeckel** [comment]
Closed because of inactivity ... if there are still problems, please feel free to reopen the issue.

**Comment by netravnen** [comment]
Thx for pointing me in the correct direction. I did indeed have the netbox_dns plugin installed beforehand. Due the the prior version having more stars on Github. Before discovering this active(!) fork.

```
root@netbox1 /opt/netbox # python /opt/netbox/netbox/manage.py migrate netbox_dns 
Operations to perform:
  Apply all migrations: netbox_dns
Running migrations:
  Applying netbox_dns.0001_squashed_netbox_dns_0_15... OK
  Applying netbox_dns.0020_netbox_3_4... OK
  Applying netbox_dns.0021_record_ip_address... OK
  Applying netbox_dns.0022_search... OK
  Applying netbox_dns.0023_alter_record_value... OK
  Applying netbox_dns.0024_tenancy... OK
  Applying netbox_dns.0025_ipam_coupling_cf... OK
  Applying netbox_dns.0026_domain_registration... OK
  Applying netbox_dns.0027_alter_registrar_iana_id... OK
  Applying netbox_dns.0028_rfc2317_fields... OK
```

**Comment by netravnen** [comment]
IMO, this would be helpful if mentioned as a footnote in the install docs.

**Comment by netravnen** [comment]
Verified the provided steps is the resolution to the described issue ✔️

**Comment by peteeckel** [comment]
Thanks for confirming the solution!

**Comment by peteeckel** [comment]
> IMO, this would be helpful if mentioned as a footnote in the install docs.

It's in the ones for the upcoming 0.23.0 release for NetBox 4.0.0+

https://github.com/peteeckel/netbox-plugin-dns/blob/feature/netbox-4/docs/using_netbox_dns.md#upgrading-netbox-dns-from-netbox-dns-to-netbox-plugin-dns
