### ISSUE TITLE
Unexpected error handling with conflicting CNAME entry

### ISSUE THREAD

**Issue by ben-ihelputech** [peteeckel/netbox-plugin-dns#176]
**Versions**
Python version: 3.10.12
NetBox version: 3.7.2
Plugins: 
  netbox_dns: 0.22.1
  netbox_proxbox: 0.0.5

**Describe the bug**
When I was creating a new IP address and assigned it a DNS entry, I got the error `'IPAddressForm' has no field named 'type'` when I tried to create it. It was not obvious at first what was going on, but after checking the server logs, I realized that I had a duplicate CNAME entry in the zone I was trying to add the DNS record to via the IP address create/edit screen.

**To Reproduce**
1. Create a CNAME record in a zone. (foo.example.com --> bar.example.com)
2. Create or edit an IP address from IPAM>IP Addresses
3. In the custom fields for Netbox Pluging DNS, enter the conflicting DNS entry for the zone. Name: foo, Zone: example.com
4. After saving the edit, a server error will appear and the change will not be saved. 

**Expected result**
Better error handling that tells the user that they made a conflicting DNS entry would be preferred. This way, the user would know that they are trying to create an A record where a CNAME record already exist.

**Actual result**
A generic Server Error page is display that gives little detail what caused the error.

**Screenshots**
![SCR-20240221-ioui](https://github.com/peteeckel/netbox-plugin-dns/assets/50592898/41dbb034-51cf-405d-a86b-a593627d9f06)

**Code Examples**
Log Output:
```
Feb 21 09:14:09 netbox NetBox[318146]: level=ERROR,logger=django.request,msg=Internal Server Error: /ipam/ip-addresses/2638/edit/
                                       Traceback (most recent call last):
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/models.py", line 486, in _post_clean
                                           self.instance.full_clean(exclude=exclude, validate_unique=False)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean
                                           raise ValidationError(errors)
                                       django.core.exceptions.ValidationError: {'type': ['There is already an active CNAME record for name cloud in zone [internal] example.com, no other record allowed.']}

                                       During handling of the above exception, another exception occurred:

                                       Traceback (most recent call last):
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
                                           response = get_response(request)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
                                           response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
                                           return self.dispatch(request, *args, **kwargs)
                                         File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 172, in dispatch
                                           return super().dispatch(request, *args, **kwargs)
                                         File "/opt/netbox/netbox/netbox/views/generic/base.py", line 26, in dispatch
                                           return super().dispatch(request, *args, **kwargs)
                                         File "/opt/netbox/netbox/utilities/views.py", line 99, in dispatch
                                           return super().dispatch(request, *args, **kwargs)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
                                           return handler(request, *args, **kwargs)
                                         File "/opt/netbox/netbox/netbox/views/generic/object_views.py", line 260, in post
                                           if form.is_valid():
                                         File "/opt/netbox/netbox/utilities/forms/mixins.py", line 55, in is_valid
                                           is_valid = super().is_valid()
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
                                           return self.is_bound and not self.errors
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
                                           self.full_clean()
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
                                           self._post_clean()
                                         File "/opt/netbox/netbox/netbox/forms/base.py", line 69, in _post_clean
                                           return super()._post_clean()
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/models.py", line 488, in _post_clean
                                           self._update_errors(e)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/models.py", line 460, in _update_errors
                                           self.add_error(None, errors)
                                         File "/opt/netbox/venv/lib/python3.10/site-packages/django/forms/forms.py", line 400, in add_error
                                           raise ValueError(
                                       ValueError: 'IPAddressForm' has no field named 'type'.
```

**Comment by peteeckel** [comment]
<img width="616" alt="Screenshot 2024-02-21 at 16 37 32" src="https://github.com/peteeckel/netbox-plugin-dns/assets/6815386/b2fef451-abea-49a2-92dd-f1410ea12a22">

Better that way? :-)

**Comment by ben-ihelputech** [comment]
Yes! That's much better! Certainly a seemingly insignificant change, but I'm sure it will save a lot of headaches down the road. Kudos!

**Comment by peteeckel** [comment]
Release 0.22.2 is on it's way ... should only take a few minutes.
