### ISSUE TITLE
Cannot edit IP Address when enforce_unique_records & feature_ipam_coupling both enabled

### ISSUE THREAD

**Issue by matejv** [peteeckel/netbox-plugin-dns#196]
**Versions**
NetBox Version: 3.7.3
NetBox DNS Version: 0.22.4
Python Version: 3.11.6

**Describe the bug**

When enforce_unique_records and feature_ipam_coupling are both enabled, if you try to edit an IP address that has a managed DNS record, you get an error: `There is already an active A record for name mytest in zone example.com with value 10.1.1.1/24.` The record referenced in error message is the same as that belonging to the IP Address you are editing.

**To Reproduce**

1. Enable the following in netbox configuration file:

```py
PLUGINS_CONFIG = {
    'netbox_dns': {
        'enforce_unique_records': True,
        'feature_ipam_coupling': True,

    },
}
```

2. Run `python manage.py setup_coupling` to create custom fields on ipam.IPAddress model
2. In Netbox DNS create nameserver and a forward DNS zone (example.com)
4. In IPAM IP address create a new IP Address. Set:
    - Address: 10.1.1.1/24
    - Custom fields / DNS / Name: mytest
    - Custom fields / DNS / Zone: select example.com
5. Click Create - the IP Address is created and a managed DNS record mytest.example.com is created in Netbox DNS
6. Click Edit on the same IP Address. Set:
    - Description: test changing
    - leave other fields unchanged
7. Click Save
9. The error is thrown

**Expected result**

IP Address object is updated and the managed DNS record is unaffected. 

**Actual result**

The following error is shown:

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/ipam/ip-addresses/39/edit/

Django Version: 4.2.10
Python Version: 3.11.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.forms',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'vpn',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'netbox_bgp.BGPConfig',
 'netbox_lists.ListsPluginConfig',
 'netbox_initializers.NetBoxInitializersConfig',
 'netbox_topology_views.TopologyViewsConfig',
 'netbox_attachments.NetBoxAttachmentsConfig',
 'netbox_inventory.NetBoxInventoryConfig',
 'netbox_dns.DNSConfig']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/netbox/views/generic/object_views.py", line 175, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/netbox/views/generic/base.py", line 26, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/utilities/views.py", line 106, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/netbox/views/generic/object_views.py", line 269, in post
    obj = form.save()
          ^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/ipam/forms/model_forms.py", line 385, in save
    ipaddress = super().save(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/forms/models.py", line 542, in save
    self.instance.save()
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/netbox/ipam/models/ip.py", line 891, in save
    super().save(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
    ^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/netbox_dns/signals/ipam_coupling.py", line 174, in ip_address_update_address_record
    record.save()
    ^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/netbox_dns/models/record.py", line 582, in save
    self.full_clean()
    ^^^^^^^^^^^^^^^^^
  File "/home/matej/temp/netbox-devel/netbox/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1502, in full_clean
    raise ValidationError(errors)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ValidationError at /ipam/ip-addresses/39/edit/
Exception Value: {'value': ['There is already an active A record for name mytest in zone example.com with value 10.1.1.1.']}
```

**Code Examples**

When saving IP Address a post_save signal handler `ip_address_update_address_record` is called. That is responsible for updating the DNS record if needed and calls `record.save()`. That method invokes cleanup functions including [`self.check_unique()`](https://github.com/peteeckel/netbox-plugin-dns/blob/935f6640510733500118364fd6a4f62486b0dc4b/netbox_dns/models/record.py#L478). That method selects existing records that have the same values as the current one. However it does not ignore itself. I think this fix should be sufficient:

```py
...
        records = Record.objects.filter(
            zone=self.zone,
            name=self.name,
            type=self.type,
            value=self.value,
            status__in=Record.ACTIVE_STATUS_LIST,
        ).exclude(pk=self.pk)
        if len(records):
...
```

(add `.exclude(pk=self.pk)` to existing `Record.objects.filter`)

I've done a few quick tests and it seems to work fine. Including the unique validation still working if you try to manually add another record with the same name, type & value to the same zone. 

PS: thank you for this plugin. With IPAM coupling feature this looks like the exact thing we've been needing.

**Comment by peteeckel** [comment]
Hi @matejv, this is a duplicate of #192 and has already been fixed in #193.
