### ISSUE TITLE
Migration netbox_dns.0024_tenancy dependencies reference nonexistent parent node ('tenancy', '0011_contactassignment_tags')

### ISSUE THREAD

**Issue by KimLangholz** [peteeckel/netbox-plugin-dns#63]
**Versions**
NetBox Version: 3.5.9
NetBox DNS Version: 0.19.1
Python Version: 3.11.4

**Describe the bug**
We've been using Netbox_dns plugin for ages. Friday we had no problem at all rebuilding our application. Today, we've been getting this error all day:

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/showmigrations.py", line 66, in handle
    return self.show_list(connection, options["app_label"])
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/showmigrations.py", line 85, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 276, in build_graph
    self.graph.validate_consistency()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/graph.py", line 198, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/graph.py", line 198, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/migrations/graph.py", line 60, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration netbox_dns.0024_tenancy dependencies reference nonexistent parent node ('tenancy', '0011_contactassignment_tags')
```

**Comment by peteeckel** [comment]
Hi @KimLangholz, sorry to hear that. 

The migration that the installation process is stumbling over (`0011_contactassignment_tags`) has been introduced in NetBox 3.6.0, and unfortunately `makemigrations` picked it up during the build process. Actually, however, I don't require it in the code, so it should be fine to make the NetBox DNS migration depend on its predecessor `0010_tenant_relax_uniqueness` instead.

I'll push a new release in a couple of minutes, please try it and let me know if it fixes your issue.

**Comment by peteeckel** [comment]
0.19.2 is out now. Please try it and let's see if it fixes your issue.

**Comment by KimLangholz** [comment]
Impressive resolve time. 

Fix works brilliantly. 

Thanks a lot @peteeckel !
